name: Build+Test

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - uses: actions/checkout@v2

      - name: Cache eslint
        uses: actions/cache@v2
        env:
          cache-name: cache-eslint
        with:
          path: ~/.eslintcache
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('.eslintrc') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('.eslintrc') }}
            ${{ runner.os }}-${{ env.cache-name }}-

      # Cypress recommends to cache ~/.cache and not to cache node_modules, see
      # https://docs.cypress.io/guides/guides/continuous-integration.html#Caching
      - name: Cache yarn and cypress
        uses: actions/cache@v2
        env:
          cache-name: cache-yarn-and-cypress
        with:
          path: ~/.cache
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('yarn.lock') }}
            ${{ runner.os }}-${{ env.cache-name }}-

      - name: Install
        run: yarn install --frozen-lockfile --prefer-offline

      - name: Test
        run: yarn test

      - name: Lint
        run: yarn lint

      - name: Build
        run: yarn build

      - name: Cypress Browser Tests
        uses: cypress-io/github-action@v2
        with:
          start: yarn start

      - name: Archive Cypress screenshots
        uses: actions/upload-artifact@v2
        with:
          name: cypress-screenshots
          path: cypress/screenshots/**/*

      - name: Archive Cypress videos
        uses: actions/upload-artifact@v2
        with:
          name: cypress-videos
          path: cypress/videos/**/*
